server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest


servers:
    name: "hi"
    - id: "skt"
    - id: "ktf"
    - id: "lgt"
