server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest

authinfo:
    host: 172.16.0.107
    port: 14001

tsinfo:
    smts:
        - tsid: skt
          port: 11001
          valid: Y
        - tsid: ktf
          port: 21001
          valid: Y
    dbinfo:
        ip: 172.16.0.107
        port: 3306
        dbname: smts
