server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest


tsmt:
    server:
        -skt:
            name: "skt"
            sms:
                port: 11001
                recvque: "smt_sk1.que"

        -ktf:
            name: "ktf"
            sms:
                port: 21001
                recvque: "smt_kt1.que"
        -lgt:
            name: "lgt"
            sms:
                port: 31001
                recvque: "smt_lgt1.que"
