server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest


tsmt:
    server:
        -name: "skt"
         port: 11001
         recvque: "smt_sk1.que"

        -name: "ktf"
         port: 21001
         recvque: "smt_kt1.que"
        -name: "lgt"
         port: 31001
         recvque: "smt_lgt1.que"
