server:
  port: 8090

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest

authinfo:
    host: 172.16.0.107
    port: 14001

tsinfo:
    smt_skt:
        ip: 172.16.2.55
        port: 11001
        valid: Y
    smt_ktf:
        ip: 172.16.2.55
        port: 21001
        valid: Y
    smt_lgt:
        ip: 172.16.2.55
        port: 31001
        valid: Y

dbinfo:
    ip: 172.16.0.107
    port: 3306
    dbname: smts

env:
