server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest

skt:
    sms:
        ip: "172.16.2.55"
        port: 11001
        recvque: "smt_sk1.que"
