server:
  port: 8090

message:
  act: "act-hello"

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest


env:
    smts:
        - name: skt
          port: 11001
        - name: kft
          port: 21001
    mmts:
        - name: skt
          port: 13001
        - name: ktf
          port: 23001
