server:
  port: 8090

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest

authinfo:
    host: 172.16.0.107
    port: 14001

tsinfo:
    smts:
        - tsid: smt_skt
          port: 11001
          valid: Y
        - tsid: smt_ktf
          port: 21001
          valid: Y
        - tsid: smt_lgt
          port: 31001
          valid: Y

dbinfo:
    ip: 172.16.0.107
    port: 3306
    dbname: smts

env:
