/* soapStub.h
   Generated by gSOAP 2.8.4 from mm7.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (7)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	char *mm7__TransactionID;	/* mustUnderstand */
};
#endif

#endif

#ifndef SOAP_TYPE_StatusTree
#define SOAP_TYPE_StatusTree (8)
/* StatusTree */
struct StatusTree
{
public:
	char *StatusCode;	/* optional element of type xsd:string */
	char *StatusText;	/* optional element of type xsd:string */
	char *Detail;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mm7__DeliverRsp
#define SOAP_TYPE_mm7__DeliverRsp (9)
/* mm7:DeliverRsp */
struct mm7__DeliverRsp
{
public:
	char *MM7Version;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *ServiceCode;	/* optional element of type xsd:string */
	struct StatusTree *Status;	/* optional element of type StatusTree */
};
#endif

#ifndef SOAP_TYPE_mm7__DeliverReq
#define SOAP_TYPE_mm7__DeliverReq (13)
/* mm7:DeliverReq */
struct mm7__DeliverReq
{
public:
	char *MM7Version;	/* optional element of type xsd:string */
	char *MMSRelayServerID;	/* optional element of type xsd:string */
	char *Sender;	/* optional element of type xsd:string */
	char *Recipients;	/* optional element of type xsd:string */
	char *TimeStamp;	/* optional element of type xsd:string */
	char *Subject;	/* optional element of type xsd:string */
	char *Content;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (14)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type env:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (16)
/* env:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (19)
/* env:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (20)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type env:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type env:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type env:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type env:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 mm7__DeliverReq(struct soap*, char *MM7Version, char *MMSRelayServerID, char *Sender, char *Recipients, char *TimeStamp, char *Subject, char *Content, struct mm7__DeliverRsp *DeliverRsp);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_mm7__DeliverReq(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_mm7__DeliverReq(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *MM7Version, char *MMSRelayServerID, char *Sender, char *Recipients, char *TimeStamp, char *Subject, char *Content, struct mm7__DeliverRsp *DeliverRsp);

#endif

/* End of soapStub.h */
